version: '3'
services: 
  node: 
    build: 
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    networks: 
      - app-network

  nginx:
    image: nginx:stable-alpine
    ports: 
      - "80:80"
      - "443:443"
    volumes: 
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - web-root:/var/www/html
    depends_on: 
      - node
    networks: 
      - app-network

  certbot:
    image: certbot/certbot
    volumes: 
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - web-root:/var/www/html
    depends_on: 
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email artysed@gmail.com --agree-tos --no-eff-email --staging -d artysed.com  -d www.artysed.com

volumes: 
  web-root:
networks: 
  app-network:
    driver: bridge