version: '3'
services: 
  nodejs: 
    image: ghcr.io/flyoozes/artysed:latest
    container_name: nodejs
    networks: 
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports: 
      - "80:80"
      - "443:443"
    volumes: 
      - ./app.conf:/etc/nginx/conf.d
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      # - ./data/certbot/conf:/etc/letsencrypt
      # - ./data/certbot/www:/var/www/certbot
    depends_on: 
      - nodejs
    networks: 
      - app-network

  certbot:
    image: certbot/certbot
    volumes: 
      # - ./data/certbot/conf:/etc/letsencrypt
      # - ./data/certbot/www:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html

    depends_on: 
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email artysed@gmail.com --agree-tos --no-eff-email --staging -d artysed.com  -d www.artysed.com

volumes: 
  certbot-etc:
  certbot-var:
  web-root:
    driver: local

networks: 
  app-network:
    driver: bridge