version: '3'
services: 
  nodejs: 
    image: ghcr.io/flyoozes/artysed:latest
    container_name: nodejs
    networks: 
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports: 
      - "80:80"
      - "443:443"
    volumes: 
      - ./data/nginx:/etc/nginx/conf.d
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on: 
      - nodejs
    networks: 
      - app-network

  certbot:
    image: certbot/certbot
    volumes: 
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html

    depends_on: 
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email artysed@gmail.com --agree-tos --no-eff-email --force-renewal -d artysed.com -d www.artysed.com

volumes: 
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts: 
      type: none
      device: /home/artysed/node_project/views/
      o: bind

networks: 
  app-network:
    driver: bridge